Volcano Plot: Fix an error when one of the groups is empty
If either of the test groups is empty, scipy.stats.ttest_ind returns
single scalar values, causing an:

     IndexError: invalid index to scalar variable