Differential Expression: Fix an error when using numpy 1.13
The widget would set/use a single element array for the `cuts` in
`select_p_best`. This would later result in an:

    TypeError: only integer scalar arrays can be converted to a scalar index